Repository AY2324S1-CS2103T-T10-4/tp, pull requests merged in 2023-10, with the labels that each got.

#23 Add PPP and information to AboutUs
  docs/AboutUs.md
  docs/team/li-rongzhi.md
  docs/team/lunaroddity.md
Labels: documentation

#24 Add UI mockup
  docs/images/Ui.png
Labels: documentation

#25 Update site-wide settings to reflect "SOCareers" in navigation bar
  docs/_sass/minima/_base.scss
Labels: documentation

#27 Update README.md for SOCareers
  README.md
Labels: documentation

#81 Add the list p command, a skeleton for the list c command, and update relevant tests for list p.
  src/main/java/seedu/address/logic/commands/listcommands/ListCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListCompaniesCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListPersonsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/listcommands/ListCompaniesCommandTest.java
  src/test/java/seedu/address/logic/listcommands/ListPersonsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Story, priority.High

#101 Fix exceptions in view and delete from PR#94
  src/main/java/seedu/address/logic/commands/addcommands/AddCommand.java
  src/main/java/seedu/address/logic/commands/deletecommands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCompanyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: type.Chore, type.Bug

#108 Add support for Internship classes within a Company class, and json loading support for Internships
  build.gradle
  src/main/java/seedu/address/commons/util/DateTimeParserUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/editcommand/EditCompanyCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/internship/Internship.java
  src/main/java/seedu/address/model/company/internship/InternshipDescription.java
  src/main/java/seedu/address/model/company/internship/InternshipInterviewDateTime.java
  src/main/java/seedu/address/model/company/internship/InternshipName.java
  src/main/java/seedu/address/model/util/CompanySampleDataUtil.java
  src/main/java/seedu/address/model/util/InternshipSampleDataUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidCompanyAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidCompanyAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateCompanyAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidCompanyAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
  src/test/java/seedu/address/commons/util/DateTimeParserUtilTest.java
  src/test/java/seedu/address/logic/commands/addcommands/AddCompanyCommandIntegrationTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/company/CompanyTest.java
  src/test/java/seedu/address/model/company/internship/InternshipDescriptionTest.java
  src/test/java/seedu/address/model/company/internship/InternshipInterviewDateTimeTest.java
  src/test/java/seedu/address/model/company/internship/InternshipNameTest.java
  src/test/java/seedu/address/model/company/internship/InternshipTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/EditCompanyDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/TypicalCompanies.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: priority.High, type.Chore

#115 Update some DG diagrams to make them more readable
  docs/DeveloperGuide.md
  docs/diagrams/CompanyModelDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/CompanyModelDiagram.png
  docs/images/ModelClassDiagram.png
Labels: priority.Medium, type.Chore

#117 Update UG with details for adding internships
  docs/UserGuide.md
Labels: type.Chore

#120 Update the UG to include screenshots of the new UI for all commands
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addCompany.png
  docs/images/addPerson.png
  docs/images/deleteCompany.png
  docs/images/deletePerson.png
  docs/images/findCompanyByNameAndTag.png
  docs/images/findPersonByNameAndTag.png
  docs/images/listCompanies.png
  docs/images/listPersons.png
  docs/images/viewCompany.png
  docs/images/viewPerson.png
Labels: priority.Medium, type.Chore

#121 Update the DG to include enhancement of the `find` command
  docs/DeveloperGuide.md
  docs/diagrams/FindPersonSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/FindPersonSequenceDiagram.png
  docs/images/tim-siu.png
  docs/team/tim-siu.md
Labels: priority.Medium, type.Chore

#126 Enable Assertions
  build.gradle
Labels: priority.High, severity.High, severity.Urgent
